### ISSUE TITLE
Unable to extract text 

### ISSUE THREAD

**Issue by chinseng85** [CommitteeOfZero/sc3tools#3]
I'm using this tool to extract text from YU-NO scripts, and I'm able to extract most of the text from the scx files. However, this tool is failed to extract text from some of the scx. It shows `Error: unrecognized format.`

The command i used was `sc3tools extract-text YNS_02_03.scx sg0`

Attach one of the scx file, if you need it to debug.
[YNS_02_03.scx](https://mega.nz/file/ShZRESIL#h8L-VsvzwDyZv-eMu1IJg-M24Jnc8h9131IZKxI3Fww)

**Comment by chinseng85** [comment]
Turned out the problem is the script header not set to SC3. After changing the header to SC3 problem solved.

**Comment by AceanGuy** [comment]
how did you set the scipt header to sc3?
