### ISSUE TITLE
Robotics;Note DaSH Elite  replace-text Error: unrecognized format.

### ISSUE THREAD

**Issue by l0ve2s** [CommitteeOfZero/sc3tools#4]
![1](https://user-images.githubusercontent.com/88938174/164024365-0fee00d3-a8ed-4e4f-ba5a-2c8de88d3aa5.png)
[RN01_00A_00.zip](https://github.com/CommitteeOfZero/sc3tools/files/8513741/RN01_00A_00.zip)
Hello,  I am trying to use the sc3tools to insert.msb files and noticed an issue with the .msb for Robotics;Note DaSH Elite 
RN01_00A_00.msb file sc3tools replace-text command
Error: unrecognized format.

**Comment by Enorovan** [comment]
This *should* be fixed in version 2.2.0
